// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class AppAssets {
  const AppAssets._();

  /// {@macro assets_generator.assets_notlamedownloader_svg.preview}
  static const String assets_notlamedownloader_svg =
      'assets/NotLameDownloader.svg';

  /// {@macro assets_generator.assets_file_png.preview}
  static const String assets_file_png = 'assets/file.png';
}
